#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-only
"""Generate unit/mc7plus_test_vectors.h from the zymatik reference decoder.

Picks representative corpus blobs, decodes them with zymatik (the source of
truth) and embeds code + expected assembler text so `test_mc7plus` gates the
C port against the reference without needing python at build time.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ZROOT = HERE.parent.parent / "zymatik"
sys.path.insert(0, str(ZROOT))

from zymatik.mc7plus.asm.disasm import decode_code          # noqa: E402
from zymatik.mc7plus.asm.text import render_statements      # noqa: E402

CORPUS = ZROOT / "tests" / "corpus"

# representative mix: pure-native blocks, classic-language corpus members,
# everything with wide operand coverage
PICKS = [
    "bins2/mc7plus-lab2.AddMul@1_FC17.bin",
    "bins2/mc7plus-lab2.B01@1_FB1.bin",
    "bins2/mc7plus-lab2.DoubleIt@1_FC18.bin",
    "bins2/mc7plus-lab2.InnerFB@1_FB11.bin",
]


def pick_wide():
    """one corpus file with memory/db/real operand coverage if present."""
    import re
    best = None
    for p in sorted((CORPUS / "mc7").glob("*.bin")):
        try:
            txt = render_statements(decode_code(p.read_bytes()))
        except Exception:
            continue
        score = 0
        for pat, w in ((r"%I", 2), (r"%Q", 2), (r"%M", 2), (r"DB\d+", 3),
                       (r"@\w+", 1), (r":\w+", 1), (r"[0-9.]+[L]?", 1),
                       (r"\{", 1), (r"\[", 3)):
            score += len(re.findall(pat, txt)) * w
        if best is None or score > best[0]:
            best = (score, p, txt)
    return best[1] if best else None


def c_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return '"%s"' % out


def main() -> int:
    cases = []
    for rel in PICKS:
        p = CORPUS / rel
        code = p.read_bytes()
        cases.append((rel, code, render_statements(decode_code(code))))
    wide = pick_wide()
    if wide:
        rel = "mc7/" + wide.name
        code = wide.read_bytes()
        cases.append((rel, code, render_statements(decode_code(code))))

    out = []
    w = out.append
    w("/* AUTO-GENERATED by tools/gen_mc7plus_tests.py -- DO NOT EDIT.")
    w(" * Expected text comes from the zymatik python reference decoder.")
    w(" */")
    w("#ifndef LIB_MC7PLUS_TEST_VECTORS_H")
    w("#define LIB_MC7PLUS_TEST_VECTORS_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w("typedef struct {")
    w("\tconst char *name;")
    w("\tconst uint8_t *code;")
    w("\tsize_t code_len;")
    w("\tconst char *expected;")
    w("} mc7p_test_case_t;")
    w("")
    w("static const mc7p_test_case_t mc7p_test_cases[] = {")
    for rel, code, text in cases:
        hx = ",".join("0x%02x" % b for b in code)
        w("\t{ %s," % c_str(rel))
        w("\t  (const uint8_t[]){%s}, %d," % (hx, len(code)))
        w("\t  %s }," % c_str(text))
    w("};")
    w("#endif /* LIB_MC7PLUS_TEST_VECTORS_H */")

    dest = HERE.parent / "unit" / "mc7plus_test_vectors.h"
    dest.write_text("\n".join(out) + "\n")
    print("wrote %s (%d cases)" % (dest, len(cases)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
